<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\uploads\project\**" />
    <Compile Remove="wwwroot\uploads\task\**" />
    <Content Remove="wwwroot\uploads\project\**" />
    <Content Remove="wwwroot\uploads\task\**" />
    <EmbeddedResource Remove="wwwroot\uploads\project\**" />
    <EmbeddedResource Remove="wwwroot\uploads\task\**" />
    <None Remove="wwwroot\uploads\project\**" />
    <None Remove="wwwroot\uploads\task\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\home.html" />
    <Content Remove="wwwroot\login.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenAI" Version="2.10.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
